# Site settings
title: KieferWare
email: f/xayrbvje
url: https://kieferware.com
description: "KieferWare — software, firmware, and electronics engineering by Kurt Kiefer, specializing in FPGA development, embedded Linux, and embedded systems design."
keywords: "software, firmware, fpga, electronics, embedded systems, research, development"
skills: "Software · Firmware · FPGA · Embedded Systems"
meta_author: Kurt Kiefer

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: kieferware

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 0d0221
  primary-rgb: "13,2,33"
  secondary: 4a1080
  secondary-dark: b967ff

# Footer settings
footer:
  copyright: KieferWare
  location: About
  social: Around the Web

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/kiefer/
  - title: github
    url: https://github.com/kekiefer

# Postal address (add as many lines as necessary)
address:
  - line: Kurt Kiefer
  - line: Goleta, CA 93117

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: /portfolio/:title/
